// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UzCB6KNXy06AuhdgV2IxFGdcjzAJrYY',
    appId: '1:627587263903:web:8ff74ad67342cd212b61aa',
    messagingSenderId: '627587263903',
    projectId: 'friendlychat-db3ea',
    authDomain: 'friendlychat-db3ea.firebaseapp.com',
    databaseURL: 'https://friendlychat-db3ea.firebaseio.com',
    storageBucket: 'friendlychat-db3ea.appspot.com',
    measurementId: 'G-W4Z4TXVJ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-CTZb-qh4vvMqJPOiQZtd7GA6h6x11c',
    appId: '1:627587263903:android:54628c21c6e5975d2b61aa',
    messagingSenderId: '627587263903',
    projectId: 'friendlychat-db3ea',
    databaseURL: 'https://friendlychat-db3ea.firebaseio.com',
    storageBucket: 'friendlychat-db3ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAILj6xsFUruezEWHi8zXDGD7X3gbuz3T4',
    appId: '1:627587263903:ios:ac4c7527f44f7b902b61aa',
    messagingSenderId: '627587263903',
    projectId: 'friendlychat-db3ea',
    databaseURL: 'https://friendlychat-db3ea.firebaseio.com',
    storageBucket: 'friendlychat-db3ea.appspot.com',
    androidClientId: '627587263903-qbae49q8qdstcth7a6ca48bho5jrjv80.apps.googleusercontent.com',
    iosClientId: '627587263903-kdl1as2desoj2a96kpvuh0kk2rup1cbi.apps.googleusercontent.com',
    iosBundleId: 'com.flow.chat.flowChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAILj6xsFUruezEWHi8zXDGD7X3gbuz3T4',
    appId: '1:627587263903:ios:ac4c7527f44f7b902b61aa',
    messagingSenderId: '627587263903',
    projectId: 'friendlychat-db3ea',
    databaseURL: 'https://friendlychat-db3ea.firebaseio.com',
    storageBucket: 'friendlychat-db3ea.appspot.com',
    androidClientId: '627587263903-qbae49q8qdstcth7a6ca48bho5jrjv80.apps.googleusercontent.com',
    iosClientId: '627587263903-kdl1as2desoj2a96kpvuh0kk2rup1cbi.apps.googleusercontent.com',
    iosBundleId: 'com.flow.chat.flowChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0UzCB6KNXy06AuhdgV2IxFGdcjzAJrYY',
    appId: '1:627587263903:web:a510fc315399a7c42b61aa',
    messagingSenderId: '627587263903',
    projectId: 'friendlychat-db3ea',
    authDomain: 'friendlychat-db3ea.firebaseapp.com',
    databaseURL: 'https://friendlychat-db3ea.firebaseio.com',
    storageBucket: 'friendlychat-db3ea.appspot.com',
    measurementId: 'G-GML1YTNL05',
  );
}
